name = "semiz-kaltenleutgeben"
compatibility_date = "2024-01-01"

[build]
  command = "pnpm build"

[site]
  bucket = "./dist"

[[routes]]
  pattern = "semiz-kaltenleutgeben.pages.dev/*"
  zone_name = "pages.dev"
